version: '3.8'

services:
  prometheus-local:
    image: prom/prometheus:latest
    volumes:
      - ./deploy/prometheus/prometheus.local.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    restart: always

  grafana-local:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    # You can persist data if you want
    # volumes:
    #   - grafana_local_data:/var/lib/grafana
    restart: always

# volumes:
#   grafana_local_data:
