version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: housing_user
      POSTGRES_PASSWORD: housing_password
      POSTGRES_DB: housing_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

volumes:
  db_data:
  mongo_data:
  grafana_data:
