name: OCI Provisioning Retry

on:
  schedule:
    - cron: '0 * * * *'  # Once per hour
  workflow_dispatch:        # Allow manual trigger

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init & Apply
        working-directory: ./terraform
        env:
          TF_VAR_tenancy_ocid: ${{ secrets.OCI_TENANCY_OCID }}
          TF_VAR_user_ocid: ${{ secrets.OCI_USER_OCID }}
          TF_VAR_fingerprint: ${{ secrets.OCI_FINGERPRINT }}
          TF_VAR_private_key: ${{ secrets.OCI_API_PRIVATE_KEY }}
          TF_VAR_region: "ap-chuncheon-1"
          TF_VAR_compartment_ocid: ${{ secrets.OCI_COMPARTMENT_OCID }}
          TF_VAR_ssh_public_key: ${{ secrets.OCI_SSH_PUBLIC_KEY }}
          TF_VAR_monitoring_source_cidr: ${{ secrets.OCI_MONITORING_SOURCE_CIDR }}
        run: |
          terraform init -reconfigure -backend-config="address=${{ secrets.OCI_BACKEND_URL }}"
          terraform apply -auto-approve -lock=false
